apiVersion: v1
kind: Service
metadata:
  name: web-deploy1
  labels:
    app: web-deploy1
spec:
  ports:
  - port: 80
    nodePort: 32750
  selector:
     env: production
     dc: "2"
  type: NodePort
